remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:month/:day/:title

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
